/* Abhyāsa — offline shell.  Generated by scripts/pwa.js; do not edit. */
const CACHE = 'abhyasa-e4f6bc5';

self.addEventListener('install', e => {
  /* Nothing to precache: the first navigation fills the cache with the very
     bytes the browser just used, whatever the page is called. */
  self.skipWaiting();
});

self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key !== CACHE && key.startsWith('abhyasa-')) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) return;

  /* The page itself: network first, so a redeploy is seen; the cache is what
     answers when there is no network. */
  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        if (fresh && fresh.ok) (await caches.open(CACHE)).put(req, fresh.clone());
        return fresh;
      } catch (err) {
        const cache = await caches.open(CACHE);
        return (await cache.match(req))
            || (await cache.match(req, { ignoreSearch: true }))
            || (await cache.matchAll()).find(r => r && r.ok)
            || Response.error();
      }
    })());
    return;
  }

  /* Anything else the page asks for on its own origin — there is nothing at
     all in the shipped page, but a deployment may sit beside an icon file. */
  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req);
    if (hit) return hit;
    const fresh = await fetch(req);
    if (fresh && fresh.ok) cache.put(req, fresh.clone());
    return fresh;
  })());
});
