#!/usr/bin/env node
/* The installable layer: a web app manifest, and a service worker.
 *
 * Two rules shape what is here, and they pull in opposite directions.
 *
 *   The distributable is ONE file with nothing to fetch.  It has to open
 *   from file:// on a phone with no network, and scripts/build.js proves it
 *   after every build.
 *
 *   A PWA is installed off a manifest, and served offline by a service
 *   worker registered from a real, same-origin script.
 *
 * So the manifest is inlined as a data: URI, icons and all — a data: URI is
 * not a fetch, and a page carrying one is still one file.  The service
 * worker cannot be: registration refuses anything but a script URL.  It is
 * therefore written beside the page as dist/sw.js and registered at RUNTIME,
 * only when the page is being served over http(s).  Opened from file://
 * nothing is attempted and nothing breaks: the page was already offline.
 *
 * Nothing here is a backend.  The worker caches what the browser has already
 * been given and serves it back; it never reaches for anything the page did
 * not ask for itself.
 */

const NAME = 'Abhyāsa';
const DESCRIPTION = 'Sanskrit flashcards for scripture, practice and ritual — '
  + 'the practice layer for Sanskrit School.';

/* The ground the page paints, so the splash screen, the status bar and the
   app itself are one colour rather than three — --ground in app/styles.css. */
const GROUND = '#0d0d18';

/* `start_url` is deliberately NOT here, and is filled in by the page itself.
   A manifest's URLs resolve against the MANIFEST's own URL; this one travels
   as a data: URI, against which nothing relative can resolve, and Chrome
   refuses to install without a valid one.  So the page writes its own
   address in at load time — see the offline shell at the foot of app.js.
   That is also the honest answer for a single file: where it starts is
   wherever it was opened from. */
function manifest(icons) {
  return {
    name: NAME + ' — Sanskrit practice',
    short_name: NAME,
    description: DESCRIPTION,
    lang: 'en',
    dir: 'ltr',
    display: 'standalone',
    /* the app is designed for a portrait phone and the card is set for one;
       `portrait-primary` would also refuse an upside-down tablet, which is
       not something to have an opinion about */
    orientation: 'portrait',
    background_color: GROUND,
    theme_color: GROUND,
    categories: ['education', 'books'],
    icons,
  };
}



/* ── the worker ────────────────────────────────────────────────────────
   Deliberately without a precache list.  The page is one file whose name
   and path depend on where it was deployed, so a hard-coded list would be
   wrong somewhere; what the worker caches instead is what the browser
   actually asked for.  A navigation goes to the network first, so a
   redeployed page is picked up on the next visit, and falls back to the
   copy in the cache when there is no network — which is the whole promise.

   `stamp` is the build's own hash, so a new build is a new cache and the
   old one is dropped on activation. */
const worker = stamp => `/* Abhyāsa — offline shell.  Generated by scripts/pwa.js; do not edit. */
const CACHE = 'abhyasa-${stamp}';

self.addEventListener('install', e => {
  /* Nothing to precache: the first navigation fills the cache with the very
     bytes the browser just used, whatever the page is called. */
  self.skipWaiting();
});

self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key !== CACHE && key.startsWith('abhyasa-')) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) return;

  /* The page itself: network first, so a redeploy is seen; the cache is what
     answers when there is no network. */
  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        if (fresh && fresh.ok) (await caches.open(CACHE)).put(req, fresh.clone());
        return fresh;
      } catch (err) {
        const cache = await caches.open(CACHE);
        return (await cache.match(req))
            || (await cache.match(req, { ignoreSearch: true }))
            || (await cache.matchAll()).find(r => r && r.ok)
            || Response.error();
      }
    })());
    return;
  }

  /* Anything else the page asks for on its own origin — there is nothing at
     all in the shipped page, but a deployment may sit beside an icon file. */
  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req);
    if (hit) return hit;
    const fresh = await fetch(req);
    if (fresh && fresh.ok) cache.put(req, fresh.clone());
    return fresh;
  })());
});
`;

module.exports = { manifest, worker, NAME, DESCRIPTION, GROUND };
